### POST establishments
POST http://localhost:3000/establishments
Content-Type: application/json

{
    "name": "KNX Parking",
    "cnpj": "15652258000140",
    "address": "Rua XYZ 800",
    "phone": "",
    "car_parking_qty": 50
}


### GET establishment
GET http://localhost:3000/establishments/7a442075-eb01-46b4-b769-2738cd755c9f


### GET all establishments
GET http://localhost:3000/establishments

### PATCH establishment
PATCH http://localhost:3000/establishments/7a442075-eb01-46b4-b769-2738cd755c9f
Content-Type: application/json

{
    "name": "KNX Parking Ltda"
}

### DELETE establishment
DELETE http://localhost:3000/establishments/312c3d7f-ecab-4567-a410-ebb8cebc4198