### POST vehicles
POST http://localhost:3000/vehicles
Content-Type: application/json

{
    "brand": "Chevrolet",
    "model": "Prisma 1.4 LTZ 2018",
    "color": "Preto",
    "license_plate": "FBI6H48",
    "type": "sedan"
}


### GET vehicles
GET http://localhost:3000/vehicles/f8f70169-ed42-456b-8f47-3dc7a26d6209


### GET all vehicles
GET http://localhost:3000/vehicles

### PATCH vehicles
PATCH http://localhost:3000/vehicles/f8f70169-ed42-456b-8f47-3dc7a26d6209
Content-Type: application/json

{
    "model": "Prisma 1.4 2018"
}

### DELETE vehicles
DELETE http://localhost:3000/vehicles/f8f70169-ed42-456b-8f47-3dc7a26d6209